### ISSUE TITLE
Add AvalonEdit 

### ISSUE THREAD

**Issue by CreateLab** [CreateLab/AStalker#1]
Add AvalonEdit(https://github.com/AvaloniaUI/AvaloniaEdit) to format body.

**Comment by CreateLab** [comment]
has problems with binding content. Add avalonEdit, add mvvm binding property to it. Binding works, but it's no visualization in view.
Here view https://github.com/CreateLab/NeBrowser/blob/master/Views/MainWindow.xaml#L199 .
Here my binding wrapper https://github.com/CreateLab/NeBrowser/blob/master/Controls/BindableTextEditor.cs#L24
Here my view model https://github.com/CreateLab/NeBrowser/blob/master/ViewModels/MainWindowViewModel.cs#L92

**Comment by b00ted** [comment]
For me it's start working after adding this lines into App.xaml
(The style block is a copy of https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/src/AvaloniaEdit/TextEditor.xaml with selector changed)
```		
<StyleInclude Source="avares://AvaloniaEdit/AvaloniaEdit.xaml" />
<Style Selector="localControls|BindableTextEditor">
	<Setter Property="Template">
		<ControlTemplate>
			<Border BorderBrush="{TemplateBinding BorderBrush}"
					BorderThickness="{TemplateBinding BorderThickness}">
				<ScrollViewer Focusable="False"
							  Name="PART_ScrollViewer"
							  VerticalScrollBarVisibility="{TemplateBinding VerticalScrollBarVisibility}"
							  HorizontalScrollBarVisibility="{TemplateBinding HorizontalScrollBarVisibility}"
							  VerticalContentAlignment="Top"
							  HorizontalContentAlignment="Left"
							  Padding="{TemplateBinding Padding}" />
			</Border>
		</ControlTemplate>
	</Setter>
</Style>
```

and namespace `xmlns:localControls="clr-namespace:NeBrowser.Controls"`
